### PR TITLE
Feature: query param naming and format

### LINKED ISSUE #13: CamelCased query params
For consistency as our APIs are camelCased I think query params should also be camelCased.
#### Example

`/posts?ordering=published_on` => `/posts?ordering=publishedOn`

### PR DESCRIPTION
**Pull request by jamesjwarren**
Just adds a little note about query param naming and formatting.

Fixes #13

### CODE REVIEW

**Comment by krak3n** [comment]
@SOON-dorks whats everyone think?

**Comment by edoparearyee** [comment]
:+1: agree

**Comment by radeklos** [comment]
I don't - for ordering it means to create a map between camel and snake syntax and manually create all django filters.. 

But we agreed to use camelCase. I'll change it.

**Comment by krak3n** [comment]
The war of :snake: vs :camel: continues! lol

Seeing as we picked camel case for our JSON attributes it makes sense to do the same for query params. I agree with @radeklos it goes against every python bone in my body but consistency is key across systems and python is in the minority here.

:+1:

**Comment by gregatsoon** [comment]
We chose :camel: so agree we should make it consistent.

Thinking out loud here but could we just choose short lowercase query params that don't need :camel: :briefcase: i.e ord (order), pub (published on) - as long as it's documented it really doesn't matter what we call the params.

That feel like an easy win here.

**Comment by krak3n** [comment]
Cool, merging this then, names of query params is implementation detail and down to developer discretion.

**Pull request merged**
