### PR TITLE
Notes on OPTIONS

### PR DESCRIPTION
**Pull request by krak3n**
Fixes issue #4 raised by @radeklos 

@thisissoon/owners let me know what you think. This should be the last one!

### CODE REVIEW

**Comment by edoparearyee** [comment]
:+1:

**Comment by radeklos** [comment]
:+1:

**Comment by jamesjwarren** [comment]
:+1:

**Comment by gregatsoon** [comment]
Ah, bloody OPTIONS. Good shout @radeklos :+1:

**Pull request merged**
